import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ConnectButton } from '@rainbow-me/rainbowkit';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Rafael</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rafa.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello!  👋🏻  I am <a href="https://twitter.com/Rafael41603219">rafaelfuentes.eth! 👨🏻‍💻</a>
        </h1>

        <ConnectButton />

        <p className={styles.description}>
          I am blockchain and web3 developer, consultant and researcher 🌎
        </p>


        <div className={styles.grid}>
          <a href="https://github.com/RafaBlockDev" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Look my github and find interesting projects in blockchain and web3! 🚀</p>
          </a>

          <a href="https://twitter.com/Rafael41603219" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p>Find me on Twitter where I share and tweet very good content! 👻</p>
          </a>

          <a
            href="https://www.linkedin.com/in/rafael-f-b4809120a/"
            className={styles.card}
          >
            <h2>LinkedIn &rarr;</h2>
            <p>Found my experiences, my skills, posts and my professional profile! 😎</p>
          </a>

          <a
          href=""
            className={styles.card}
          >
            <h2>Articles &rarr;</h2>
            <p>
              Look my articles, my research, and tutorials done for me, about blockchain! 📚
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Cypherpunk and anarchist
          <span className={styles.logo}>
            <Image src="/rafa.png" alt="Rafa Face" width={20} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
